#!/bin/sh

# Wrapper around ocamldebug for Coq

# This file is to be launched via the generated script ocamldebug-coq,
# which will set the env variables $OCAMLDEBUG, $CAMLP4LIB, $COQTOP

exec $OCAMLDEBUG \
	-I $CAMLP4LIB \
	-I $COQTOP \
	-I $COQTOP/config -I $COQTOP/printing -I $COQTOP/grammar \
	-I $COQTOP/lib -I $COQTOP/intf -I $COQTOP/kernel \
	-I $COQTOP/library -I $COQTOP/pretyping -I $COQTOP/parsing \
        -I $COQTOP/interp -I $COQTOP/proofs -I $COQTOP/tactics \
	-I $COQTOP/toplevel -I $COQTOP/dev -I $COQTOP/config \
        -I $COQTOP/plugins/cc         -I $COQTOP/plugins/dp \
        -I $COQTOP/plugins/extraction -I $COQTOP/plugins/field \
        -I $COQTOP/plugins/firstorder -I $COQTOP/plugins/fourier \
        -I $COQTOP/plugins/funind     -I $COQTOP/plugins/groebner \
        -I $COQTOP/plugins/interface  -I $COQTOP/plugins/micromega \
        -I $COQTOP/plugins/omega      -I $COQTOP/plugins/quote \
        -I $COQTOP/plugins/ring       -I $COQTOP/plugins/romega \
	-I $COQTOP/plugins/rtauto     -I $COQTOP/plugins/setoid_ring \
        -I $COQTOP/plugins/subtac     -I $COQTOP/plugins/syntax \
        -I $COQTOP/plugins/xml \
        -I $COQTOP/ide \
	"$@"
